### ISSUE TITLE
[Service Provider] User can browse posted tasks by the customer and make an offer

### ISSUE THREAD

**Issue by engramar** [codesydney/migram-frontend#185]
### Current status
- [x] Testing started
- [x] Testing ongoing
- [x] Testing passed

**Comment by engramar** [comment]
After logging in as a service provider, I can see the listings to make an offer which is ggod. 
![image](https://user-images.githubusercontent.com/7553347/226431261-744e1779-acae-4d29-be30-a66ec9427d9c.png)

**Comment by engramar** [comment]
Looks perfect. 
![image](https://user-images.githubusercontent.com/7553347/226431828-d3e3fdd2-902e-4f48-b48d-502bf89d6819.png)

**Comment by engramar** [comment]
Negative testing: Tried making an offer for the same listing multiple times and it appears the app stopped.
![image](https://user-images.githubusercontent.com/7553347/226432161-3a274909-ef54-4df7-a492-1b89eb636417.png)

**Comment by engramar** [comment]
After signing out, below exceptions persist.
![image](https://user-images.githubusercontent.com/7553347/226432679-c1b8b2c9-a71b-4fe2-9f6b-5d0b926bffeb.png)

**Comment by engramar** [comment]
and when I tried logging in again, I got the below exception this time.
![image](https://user-images.githubusercontent.com/7553347/226432951-f5224f57-3af9-4260-b059-2283963ff591.png)

**Comment by davidtaing** [comment]
1. Offer creation is going through, but get offers is getting blocked by a CORS error.
2. We can spin this out into another bug request.
3. Need to dig into this one more.

**Comment by davidtaing** [comment]
Nodemailer + misconfigured enviornment variables seems to be crashing the server when an Offer is submitted.

```
2023-03-21T08:46:43.979717+00:00 app[web.1]: 1. exports.postOffer => taskTitle:  End of lease cleaning werwerwer

2023-03-21T08:46:44.292367+00:00 app[web.1]: /app/node_modules/nodemailer/lib/smtp-connection/index.js:784

2023-03-21T08:46:44.292397+00:00 app[web.1]:             err = new Error(message);

2023-03-21T08:46:44.292398+00:00 app[web.1]:                   ^

2023-03-21T08:46:44.292399+00:00 app[web.1]: 

2023-03-21T08:46:44.292400+00:00 app[web.1]: Error: Invalid login: 535 Authentication failed: Bad username / password

2023-03-21T08:46:44.292401+00:00 app[web.1]:     at SMTPConnection._formatError (/app/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)

2023-03-21T08:46:44.292403+00:00 app[web.1]:     at SMTPConnection._actionAUTHComplete (/app/node_modules/nodemailer/lib/smtp-connection/index.js:1536:34)

2023-03-21T08:46:44.292404+00:00 app[web.1]:     at SMTPConnection.<anonymous> (/app/node_modules/nodemailer/lib/smtp-connection/index.js:540:26)

2023-03-21T08:46:44.292404+00:00 app[web.1]:     at SMTPConnection._processResponse (/app/node_modules/nodemailer/lib/smtp-connection/index.js:947:20)

2023-03-21T08:46:44.292404+00:00 app[web.1]:     at SMTPConnection._onData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:749:14)

2023-03-21T08:46:44.292405+00:00 app[web.1]:     at SMTPConnection._onSocketData (/app/node_modules/nodemailer/lib/smtp-connection/index.js:189:44)

2023-03-21T08:46:44.292405+00:00 app[web.1]:     at TLSSocket.emit (node:events:513:28)

2023-03-21T08:46:44.292406+00:00 app[web.1]:     at addChunk (node:internal/streams/readable:324:12)

2023-03-21T08:46:44.292406+00:00 app[web.1]:     at readableAddChunk (node:internal/streams/readable:297:9)

2023-03-21T08:46:44.292407+00:00 app[web.1]:     at Readable.push (node:internal/streams/readable:234:10)

2023-03-21T08:46:44.292408+00:00 app[web.1]:     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {

2023-03-21T08:46:44.292408+00:00 app[web.1]:   code: 'EAUTH',

2023-03-21T08:46:44.292409+00:00 app[web.1]:   response: '535 Authentication failed: Bad username / password',

2023-03-21T08:46:44.292409+00:00 app[web.1]:   responseCode: 535,

2023-03-21T08:46:44.292410+00:00 app[web.1]:   command: 'AUTH PLAIN'

2023-03-21T08:46:44.292410+00:00 app[web.1]: }

2023-03-21T08:46:44.292415+00:00 app[web.1]: 

2023-03-21T08:46:44.292416+00:00 app[web.1]: Node.js v18.12.1

2023-03-21T08:46:44.459485+00:00 heroku[web.1]: Process exited with status 1

2023-03-21T08:46:44.524825+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by davidtaing** [comment]
@engramar the server crashing on creating an offer should be resolved. I've tested on migram.com.au, but double check on your end.

https://github.com/codesydney/migram-backend/pull/31
https://github.com/codesydney/migram-backend/pull/32

**Comment by engramar** [comment]
Looks like I managed to send an offer. Thanks for the fix @davidtaing 
![image](https://user-images.githubusercontent.com/7553347/227704561-c1cef24c-e218-4c80-985b-7e85ec72a0ea.png)

**Comment by engramar** [comment]
All good. I will mark this as completed. However, I might just raise another potential future enhancement around multiple offers behaiour. 
![image](https://user-images.githubusercontent.com/7553347/227704687-10366d68-5c3c-4c40-a25e-6d9cf213bf81.png)
